CREATE TABLE PAYMENT_METHOD
(
PAYMENT_METHOD_ID INTEGER NOT NULL,
NAME VARCHAR(50) NULL,
DISP_NAME VARCHAR(50) NULL,
PAYMENT_TYPE VARCHAR(50) NULL
);

ALTER TABLE PAYMENT_METHOD
	ADD CONSTRAINT PK_PAYMENT_METHOD PRIMARY KEY (PAYMENT_METHOD_ID ASC);

CREATE TABLE PAYMENT_PLAN
(
PAYMENT_PLAN_ID INTEGER NOT NULL,
NET_AMOUNT numeric NULL,
TAX_AMOUNT numeric NULL,
GROSS_AMOUNT numeric NULL,
CURRENCY VARCHAR(50) NULL,
DURATION VARCHAR(50) NULL,
PAYMENT_METHOD_ID INTEGER NULL
);

ALTER TABLE PAYMENT_PLAN
	ADD CONSTRAINT PK_PAYMENT_PLAN PRIMARY KEY (PAYMENT_PLAN_ID ASC);

ALTER TABLE PAYMENT_PLAN
ADD FOREIGN KEY (PAYMENT_METHOD_ID) REFERENCES PAYMENT_METHOD(PAYMENT_METHOD_ID);